//! ICU4X plumbing shared by every i18n gap tracked in issue #124.
//!
//! Phase 0 (issue #127) of that effort. This module makes no behavior change
//! on its own — [`Locale`](crate::render::resolve::locale::Locale) still
//! answers the two questions it always has. What's here is the data-provider
//! infrastructure later phases (#128 regional decimal separators, #129
//! localized date names, #130 UAX #14 line breaking, #131 UAX #9 bidi) build
//! real features on top of.
//!
//! # Why a committed blob, not baked `compiled_data`
//!
//! ICU4X's default `compiled_data` Cargo feature bakes in *every* CLDR
//! locale — megabytes landing on the Python wheel, which #124 names as a
//! risk to measure and decide deliberately rather than discover after the
//! fact. Every `icu_*` leaf crate that ships locale data (`icu_decimal`
//! here; `icu_segmenter`/`icu_datetime` when later phases add them) is
//! therefore added to `Cargo.toml` with `default-features = false` — turning
//! `compiled_data` off is what makes the trimmed blob below the *only* copy
//! of the data instead of an addition on top of the default one.
//!
//! The trimmed data is generated by `scripts/make_icu_data.sh` into
//! `data/icu_data.blob`, which this module `include_bytes!`s and loads once
//! per thread (see `PROVIDER`'s doc below for why per-thread, not
//! process-wide), through [`icu_provider_blob::BlobDataProvider`]. This was
//! chosen over ICU4X's other trimming path — `--format baked` plus setting
//! `ICU4X_DATA_DIR` at `cargo build` time — because that path's correctness
//! depends on an environment variable being set identically across every CI
//! job that builds a wheel (`.github/workflows/ci.yml`'s `build-wheels`, 5
//! matrix legs, and `python.yml`'s release twin, another 5). That file
//! already documents, in its own comment, that `maturin-action` does *not*
//! forward arbitrary env vars into the Docker build it runs on Linux without
//! explicit `docker-options: -e ...` — and a missed leg wouldn't fail the
//! build, it would silently fall back to the full default `compiled_data`,
//! exactly the wheel-bloat risk this module exists to prevent. A committed
//! blob needs no such plumbing, in any workflow file, ever; the cost is
//! calling [`with_data_provider`] and using
//! `try_new_with_buffer_provider(provider, ...)` instead of the ergonomic
//! `try_new(...)` at each call site — a small, visible, permanent cost, not
//! a silent one.
//!
//! # Locale set
//!
//! Baked in: `und` (root, for ICU4X's locale-fallback chain) plus the 10
//! region tags actually present in `test-files/`/`test-cases/` today
//! (`ca-ES, de-AT, de-DE, en-CA, en-GB, en-US, fr-FR, it-IT, pl-PL, ru-RU`).
//! `scripts/make_icu_data.sh` is the single source of truth for this list —
//! extend it there, not here, when a later phase needs a region this doesn't
//! cover (e.g. #128's `de-CH`, which needs its own fixture before the region
//! is worth baking in at all — see the "Known simplification" comment on
//! [`Locale::from_tag`](crate::render::resolve::locale::Locale::from_tag)).
//!
//! # No Cargo feature gate
//!
//! Deliberately always-on, like `bitflags`/`quick-xml`, not optional like
//! `subset-fonts`. `subset-fonts`'s motivation is output size, a trade-off a
//! caller might reasonably decline; this is correctness plumbing for
//! behavior that already exists today and is simply wrong for non-English
//! documents (a decimal tab in the wrong place isn't an optional feature).
//! A flag would fork correct output behind a switch most consumers never
//! see — there's one wheel per OS/arch already. If the locale set above
//! grows enough for wheel size to become a real problem, the right lever is
//! trimming it in the regen script, not forking behavior.

use icu_provider_blob::BlobDataProvider;

static ICU_DATA: &[u8] = include_bytes!("data/icu_data.blob");

thread_local! {
    /// Per-thread cache: `BlobDataProvider`'s `Yoke<_, Option<Cart>>` carries
    /// an `Rc` in its `Cart` side regardless of which constructor built it
    /// (even the zero-copy `try_new_from_static_blob` path used here), so the
    /// type is `!Send`/`!Sync` and cannot live behind a process-wide `static`
    /// — confirmed by the compiler, not a design preference. `thread_local!`
    /// is the closest available reuse: one parse per thread instead of one
    /// per call, with no cross-thread sharing to prove sound.
    static PROVIDER: BlobDataProvider = BlobDataProvider::try_new_from_static_blob(ICU_DATA)
        .expect(
            "src/i18n/data/icu_data.blob is committed and regenerated by \
             scripts/make_icu_data.sh; a parse failure here means the blob \
             and the installed icu_provider_blob version have drifted",
        );
}

/// Run `f` with this thread's cached ICU4X data provider, loaded once per
/// thread from the blob committed at `src/i18n/data/icu_data.blob`
/// (regenerated by `scripts/make_icu_data.sh` — see the module doc for what's
/// baked in and why). ICU locale data is immutable reference data with no
/// mutation path anywhere in this codebase, unlike `FontRegistry`
/// (`crate::render::fonts`), which is deliberately *not* cached across
/// renders because the subset pass mutates typeface bytes in place after
/// layout — reuse here is safe on that front; see `PROVIDER`'s own doc for
/// why it's thread-local rather than process-wide.
pub fn with_data_provider<R>(f: impl FnOnce(&BlobDataProvider) -> R) -> R {
    PROVIDER.with(|provider| f(provider))
}

#[cfg(test)]
mod tests {
    use super::*;
    use fixed_decimal::Decimal;
    use icu_decimal::options::DecimalFormatterOptions;
    use icu_decimal::DecimalFormatter;

    /// Phase 0 (#127) proof: one ICU4X component, formatting through the
    /// blob-provider path every later phase reuses. Covers every locale
    /// `scripts/make_icu_data.sh` bakes in (plus root `und`), not just one —
    /// a single passing locale wouldn't distinguish "the blob has real CLDR
    /// data for the whole set" from "the blob happens to have `de-DE`".
    /// Expected strings were read off this formatter's own real output
    /// (`cargo test -- --nocapture` against a throwaway probe), not guessed:
    /// `de-AT`/`ru-RU` group with U+00A0 NO-BREAK SPACE (not a point/comma
    /// like `de-DE`), `fr-FR` with U+202F NARROW NO-BREAK SPACE, and
    /// `it-IT`/`pl-PL` don't group a 4-digit number at all — real regional
    /// divergence already visible within this small a set, which is
    /// precisely the kind of fact a hand-rolled table (`Locale::from_tag`)
    /// can't be expected to get right without a source like this behind it.
    #[test]
    fn icu_decimal_formats_via_blob_provider() {
        const CASES: &[(&str, &str)] = &[
            ("und", "1,234"),
            ("ca-ES", "1.234"),
            ("de-AT", "1\u{a0}234"),
            ("de-DE", "1.234"),
            ("en-CA", "1,234"),
            ("en-GB", "1,234"),
            ("en-US", "1,234"),
            ("fr-FR", "1\u{202f}234"),
            ("it-IT", "1234"),
            ("pl-PL", "1234"),
            ("ru-RU", "1\u{a0}234"),
        ];
        for &(tag, expected) in CASES {
            let out = with_data_provider(|provider| {
                let formatter = DecimalFormatter::try_new_with_buffer_provider(
                    provider,
                    tag.parse::<icu_locale_core::Locale>()
                        .unwrap_or_else(|e| panic!("{tag:?} is a valid BCP-47 tag: {e}"))
                        .into(),
                    DecimalFormatterOptions::default(),
                )
                .unwrap_or_else(|e| panic!("{tag} is baked into src/i18n/data/icu_data.blob: {e}"));
                formatter.format_to_string(&Decimal::from(1234))
            });
            assert_eq!(out, expected, "locale {tag}");
        }
    }
}
